import json
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path

# --- CONFIGURATION ---
# This file is generated by 02_normalize_filter.py
DATA_ROOT = Path(os.getenv("ABSS_DATA_ROOT", Path(__file__).resolve().parents[2] / "data"))
STATS_FILE = DATA_ROOT / "pmc" / "extracted" / "distribution_stats.json"
OUTPUT_DIR = Path(os.getenv("ABSS_FIGURES_ROOT", Path(__file__).resolve().parents[2] / "figures")) / "pubmed_ds"
TOP_N = 20  

# Aesthetic settings
sns.set_theme(style="whitegrid")

def plot_raw_distribution(data_dict, title, filename):
    """
    Plots horizontal bar chart for Top N Raw Headers.
    """
    if not data_dict:
        print(f"No data for {title}")
        return

    # Prepare DataFrame
    # data_dict is {header: count}
    df = pd.DataFrame(list(data_dict.items()), columns=['Header', 'Count'])
    df = df.sort_values('Count', ascending=False).head(TOP_N)

    # Plot
    plt.figure(figsize=(10, 8))
    ax = sns.barplot(
        data=df,
        x='Count',
        y='Header',
        palette='viridis',
        hue='Header',
        legend=False
    )

    # Labels
    ax.bar_label(ax.containers[0], padding=3)
    plt.title(title, fontsize=15)
    plt.xlabel("Count")
    plt.ylabel("Raw Section Header")
    plt.tight_layout()
    
    # Save
    save_path = os.path.join(OUTPUT_DIR, filename)
    plt.savefig(save_path, dpi=300)
    print(f"Saved: {save_path}")
    plt.close()

def plot_normalized_comparison(summ_dict, doc_dict, filename):
    """
    Plots grouped bar chart comparing Abstract vs Full Text after normalization.
    """
    if not summ_dict or not doc_dict:
        print("Missing normalized data.")
        return

    # Prepare DataFrame in Long Format for Seaborn
    # 1. Abstract Data
    df_summ = pd.DataFrame(list(summ_dict.items()), columns=['Section', 'Count'])
    df_summ['Source'] = 'Abstract'

    # 2. Full Text Data
    df_doc = pd.DataFrame(list(doc_dict.items()), columns=['Section', 'Count'])
    df_doc['Source'] = 'Full Text'

    # Combine
    df = pd.concat([df_summ, df_doc])
    
    # Order by canonical sections for consistency
    order = ['background', 'objectives', 'methods', 'results', 'conclusions']
    
    # Plot
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        data=df,
        x='Section',
        y='Count',
        hue='Source',
        order=order,
        palette='muted'
    )
    
    # Labels
    for container in ax.containers:
        ax.bar_label(container, padding=3)

    plt.title("After Normalization: Abstract vs. Full Text Distribution", fontsize=15)
    plt.xlabel("Normalized Section Label")
    plt.ylabel("Count")
    plt.legend(title="Data Source")
    plt.tight_layout()

    # Save
    save_path = os.path.join(OUTPUT_DIR, filename)
    plt.savefig(save_path, dpi=300)
    print(f"Saved: {save_path}")
    plt.close()

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    if not os.path.exists(STATS_FILE):
        print(f"Error: Stats file not found at {STATS_FILE}")
        print("Did you run 02_normalize_filter.py?")
        return

    print(f"Loading stats from {STATS_FILE}...")
    with open(STATS_FILE, 'r') as f:
        stats = json.load(f)

    # 1. Plot Raw Abstract
    plot_raw_distribution(
        stats.get('raw_abstract', {}), 
        f"Top {TOP_N} Raw Abstract Headers (Before Normalization)", 
        "dist_raw_abstract.png"
    )

    # 2. Plot Raw Full Text
    plot_raw_distribution(
        stats.get('raw_fulltext', {}), 
        f"Top {TOP_N} Raw Full Text Headers (Before Normalization)", 
        "dist_raw_fulltext.png"
    )

    # 3. Plot Normalized Comparison
    plot_normalized_comparison(
        stats.get('norm_abstract', {}),
        stats.get('norm_fulltext', {}),
        "dist_normalized_comparison.png"
    )

if __name__ == "__main__":
    main()